build: fix hooks

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,4 +1,50 @@
 #!/bin/sh
-powershell -windowstyle hidden -noprofile ./.githooks/EnsureConventionalCommitMessage.ps1 $1
-# c:\\users\\dwallis\\Desktop\\powershel.exe -windowstyle hidden -noprofile ./.githooks/EnsureConventionalCommitMessage.ps1 $1
-# c:\\users\\dwallis\\Desktop\\powershel.exe -noprofile ./.githooks/EnsureConventionalCommitMessage.ps1 $1
+#powershell -noexit -noprofile ./.githooks/EnsureConventionalCommitMessage.ps1 $1
+
+# commit_regex='(?-i)^(initial commit|merge [^\r\n]+|(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*))'
+# error_msg="Commit message format must match regex ${commit_regex}"
+# # if ! grep -qEi "$commit_regex" "$1"; then
+# #     echo "$error_msg" >&2
+# #     exit 1
+# # fi
+
+# MSG=$(HEAD -n1 "$1")
+# if ! [[ $MSG =~ ^(initial commit|merge [^\r\n]+|(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)) ]]; then
+
+# echo $MSG
+#     echo "$error_msg" >&2
+#     exit 1
+# fi
+
+
+
+YOUR_COMMIT_MESSAGE=$(HEAD -n1 "$1")
+
+CONVENTIONAL_COMMIT_PATTERN="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+"
+
+if ! [[ "$YOUR_COMMIT_MESSAGE" =~ $CONVENTIONAL_COMMIT_PATTERN ]]; then
+  # Commit message is not valid
+  echo "Error: Commit message is not allowed."
+  echo "Reason: Your commit message does not comply with this pattern: $CONVENTIONAL_COMMIT_PATTERN"
+  echo "Todo: Rewrite your commit message to comply with the pattern."
+  echo 'Here are some examples:'
+  echo '- "feat: Add user onboarding tutorial"'
+  echo '- "fix: Fix chat message overflow"'
+  echo '- "chore: Upgrade dependencies"'
+  echo '- "refactor: Refactor chat message component"'
+  echo '- "docs: Update README"'
+  echo '- "test: Add unit tests for chat message component"'
+  echo '- "ci: Add CI/CD pipeline"'
+  echo '- "build: Add build script"'
+  echo '- "style: Enforce code style with custom_lint"'
+  echo '- "perf: Improve performance of chat message component"'
+  echo '- "revert: Revert "feat: Add user onboarding tutorial""'
+  echo "===================================="
+  echo "❌ Commit message is invalid..."
+  echo "===================================="
+  exit 1
+else
+  echo "===================================="
+  echo "✅ Commit message is valid!"
+  echo "===================================="
+fi
